services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      networks:
      - web_network
  # db:
  #   image: postgres:16
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data/
  #   networks:
  #     - db_network
  household-manager:
    container_name: household-manager
    restart: unless-stopped
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/household-manager
    networks:
      - db_network
      - web_network
    depends_on:
      - redis
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./media:/media
      - ./wait-for.sh:/wait-for.sh  # Mount the script into the container
    command: ["/bin/sh", "/wait-for.sh"]  # Run the script when the container starts
    networks:
      - web_network
    depends_on: 
      - household-manager
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
