# Generated by Django 5.0.3 on 2024-04-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_family_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
