# Generated by Django 5.0.3 on 2024-04-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_budget_family_remove_budget_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('movies', 'Movies'), ('transportation', 'Transportation'), ('groceries', 'Groceries'), ('snacks', 'Snacks'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('education', 'Education')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('movies', 'Movies'), ('transportation', 'Transportation'), ('groceries', 'Groceries'), ('snacks', 'Snacks'), ('utilities', 'Utilities'), ('healthcare', 'Healthcare'), ('entertainment', 'Entertainment'), ('education', 'Education')], max_length=50),
        ),
    ]
