# Generated by Django 5.0.3 on 2024-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_expense_month_alter_monthlybudget_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ManyToManyField(related_name='expenses', to='home.member'),
        ),
    ]
