# Generated by Django 5.0.3 on 2024-04-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_expense_created_by_expense_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ManyToManyField(related_name='expenses', to='home.member'),
        ),
    ]
