# Generated by Django 5.0.3 on 2024-04-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_monthlybudget_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybudget',
            name='created_by',
        ),
    ]
