# Generated by Django 5.0.3 on 2024-04-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.family'),
        ),
    ]
