# Generated by Django 5.0.3 on 2024-04-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_chore_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='description',
        ),
    ]
