# Generated by Django 5.0.3 on 2024-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_chore_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='deadline',
            field=models.DateField(),
        ),
    ]
