# Generated by Django 5.0.3 on 2024-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_unreadmessage_user_unreadmessage_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
