# Generated by Django 5.0.3 on 2024-04-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_unreadmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.expense'),
        ),
    ]
