# Generated by Django 5.0.3 on 2024-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_notification_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
