# Generated by Django 5.0.3 on 2024-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_expense_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expense',
        ),
    ]
